language: go
go_import_path: github.com/constabulary/gb
go:
  - 1.4.3
  - 1.5.3
  - 1.6.2
  - tip

sudo: false

addons:
  apt:
    packages:
      - libcap-dev # integration-tests/service.v1
  ssh_known_hosts:
      - bitbucket.org

install:
  - go get -t -v ./...
  - git clone --quiet --single-branch --depth 1 https://github.com/constabulary/integration-tests.git ../integration-tests
  - echo '#!/bin/bash' > "$GOPATH/bin/sudo"
    && echo 'echo >&2 attempted sudo "$@"' >> "$GOPATH/bin/sudo"
    && chmod +x "$GOPATH/bin/sudo"

script:
  - go test -v ./...
  - ../integration-tests/run-all.bash
